PS1='\[\033[35;1m\]\u\[\033[0m\]@\[\033[31;1m\]\h \[\033[32;1m\]$PWD\[\033[0m\] [\[\033[35m\]\#\[\033[0m\]]\[\033[31m\]\$\[\033[0m\] '
alias u="cd .."
alias ll="ls -lA --color=yes | less -r -E -X"
alias l="ls -l --color=yes "
